name: success_hotel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get: ^4.6.5
  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.6
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/logo.png
    - assets/ring.png
    - assets/card.png
    - assets/key.png
